apiVersion: v1
kind: ConfigMap
metadata:
  name: tmas-config
data:
  DJANGO_ALLOWED_HOSTS: "*"
  STATIC_ENDPOINT_URL: "https://nyc3.digitaloceanspaces.com"
  STATIC_BUCKET_NAME: "tmas"
  DJANGO_LOGLEVEL: "info"
  DEBUG: "True"
  DATABASE_ENGINE: "postgresql"
