# Generated by Django 2.2.17 on 2021-01-29 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talegate', '0002_auto_20210129_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='active_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
