# Generated by Django 2.2 on 2020-02-19 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talegate', '0002_auto_20200219_0612'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Story Title')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
