# Generated by Django 2.2 on 2020-02-19 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talegate', '0003_storybook'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='storyBook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='talegate.StoryBook'),
        ),
        migrations.AlterField(
            model_name='storybook',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
