# Generated by Django 2.2.17 on 2021-02-16 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talegate', '0004_auto_20210216_0105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='excerpt',
            options={'ordering': ('-created',)},
        ),
        migrations.RenameField(
            model_name='story',
            old_name='prompt',
            new_name='title',
        ),
    ]
