# Generated by Django 2.2 on 2020-02-19 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talegate', '0004_auto_20200219_0642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='owner',
        ),
    ]
