name: Build and Push

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [master]
jobs:
  docker_build:
    runs-on: ubuntu-latest
    env:
      DJANGO_SECRET_KEY: test-key-change

    steps:
    - name: checkout code
      uses: actions/checkout@v3
    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build container
      working-directory: ./talemeastory
      run: |
        docker build -f Dockerfile \
        -t edwinperea7/webapp:latest \
        -t edwinperea7/webapp:${GITHUB_SHA::7} \
        .
    - name: Push image
      run: |
        docker push edwinperea7/webapp --all-tags

  deploy_to_kubernetes_cluster:
    name: Deploy to Kubernetes Cluster
    needs: docker_build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Set Kubernetes Context
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECTL_CONFIG }}
      - name: Deploy to Cluster
        env:
          BUILD_NUMBER: ${{ github.run_number }}
        run: |
          kubectl delete deploy tmas-app
          kubectl apply -f ./k8s/deployments/tmas-deployment.yml